# Generated by Django 5.1 on 2024-08-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoupStewChiliType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Bean', 'Bean'), ('Bisque', 'Bisque'), ('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Noodle', 'Noodle'), ('Vegetable', 'Vegetable'), ('Seafood', 'Seafood')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reynolds_cookbook.recipe')),
                ('dessert_type', models.CharField(choices=[('Cake', 'Cake'), ('Pie', 'Pie'), ('Cookies', 'Cookies'), ('Other', 'Other')], max_length=50)),
            ],
            bases=('reynolds_cookbook.recipe',),
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reynolds_cookbook.recipe')),
                ('main_feature', models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Fish', 'Fish'), ('Shrimp', 'Shrimp'), ('Vegetarian', 'Vegetarian')], max_length=50)),
            ],
            bases=('reynolds_cookbook.recipe',),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('oz', 'ounces'), ('lb', 'pounds'), ('piece', 'piece')], max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='reynolds_cookbook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='reynolds_cookbook.recipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='SoupStewChili',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reynolds_cookbook.recipe')),
                ('soup_stew_chili_types', models.ManyToManyField(to='reynolds_cookbook.soupstewchilitype')),
            ],
            bases=('reynolds_cookbook.recipe',),
        ),
    ]
