# Generated by Django 5.1 on 2024-08-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reynolds_cookbook', '0003_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('oz', 'ounces'), ('lb', 'pounds'), ('piece', 'piece'), ('can', 'can'), ('jar', 'jar'), ('package', 'package'), ('bunch', 'bunch'), ('pinch', 'pinch'), ('dash', 'dash'), ('to taste', 'to taste')], max_length=20),
        ),
    ]
