# Generated by Django 5.1 on 2024-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reynolds_cookbook', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soupstewchili',
            name='soup_stew_chili_types',
        ),
        migrations.AddField(
            model_name='soupstewchili',
            name='soup_type',
            field=models.CharField(choices=[('Chili', 'Chili'), ('Soup', 'Soup'), ('Stew', 'Stew')], default='Soup', max_length=50),
        ),
        migrations.DeleteModel(
            name='SoupStewChiliType',
        ),
    ]
